import "./globals.css";
import { Mulish } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

const mulish = Mulish({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Next App 1",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" className={mulish.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
